# Generated by Django 5.1.1 on 2024-09-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivo",
            name="nombre",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
