# Generated by Django 5.1.1 on 2024-09-28 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0004_alter_archivo_archivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompartirArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aceptado", models.BooleanField(default=False)),
                ("rechazado", models.BooleanField(default=False)),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_media.archivo",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recibido_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enviado_por",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
