# Generated by Django 5.1.1 on 2024-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0005_compartirarchivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivo",
            name="archivo",
            field=models.FileField(upload_to="archivos_usuarios/"),
        ),
    ]
