# Generated by Django 5.1.1 on 2024-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_media", "0014_alter_archivo_archivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivo",
            name="tipo",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
